INSERT INTO system_group (id, name, uuid) VALUES( (SELECT max(g.id) + 1 FROM system_group g) , 'Cadastro', '1ecbe902-b1ab-4225-9e8d-a02a915a3152');
INSERT INTO system_user_group (id, system_group_id, system_user_id) VALUES((SELECT max(ug.id) + 1 FROM system_user_group ug), (SELECT max(g.id) FROM system_group g), 1);
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Serviços', 'ServiceList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ServiceList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Clientes', 'CustomersList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'CustomersList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Address Form', 'AddressForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'AddressForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'CustomersForm', 'CustomersForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'CustomersForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'ProductForm', 'ProductForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ProductForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'TypeProductForm', 'TypeProductForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TypeProductForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'TypeServiceForm', 'TypeServiceForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TypeServiceForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'ServiceForm', 'ServiceForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ServiceForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'ProductList', 'ProductList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ProductList'));
INSERT INTO system_group (id, name, uuid) VALUES( (SELECT max(g.id) + 1 FROM system_group g) , 'Financeiro', '1ff11dc4-3cf1-4f72-babc-b7702e6d2390');
INSERT INTO system_user_group (id, system_group_id, system_user_id) VALUES((SELECT max(ug.id) + 1 FROM system_user_group ug), (SELECT max(g.id) FROM system_group g), 1);
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Contas', 'ContaHeaderList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ContaHeaderList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Categorias', 'CategoriaHeaderList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'CategoriaHeaderList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Despesas', 'DespesaList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'DespesaList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Receitas', 'ReceitaList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ReceitaList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Transações', 'TransacaoList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TransacaoList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de categoria', 'CategoriaForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'CategoriaForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Receita(Parcelas)', 'ReceitaFormParcela');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ReceitaFormParcela'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Processar Pagamento', 'ProcessarPagamentoForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ProcessarPagamentoForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Processar Recebimento', 'ProcessarRecebimentoForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ProcessarRecebimentoForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Receita', 'ReceitaForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ReceitaForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Despesa', 'DespesaForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'DespesaForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de conta', 'ContaForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'ContaForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Despesa (Parcelas)', 'DespesaFormParcela');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'DespesaFormParcela'));
INSERT INTO system_group (id, name, uuid) VALUES( (SELECT max(g.id) + 1 FROM system_group g) , 'Organização', '367dbab9-f3f2-4dbd-84c8-1ac88e68379c');
INSERT INTO system_user_group (id, system_group_id, system_user_id) VALUES((SELECT max(ug.id) + 1 FROM system_user_group ug), (SELECT max(g.id) FROM system_group g), 1);
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Planos', 'PlanoList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'PlanoList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Tarefas', 'TarefaList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TarefaList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Kanban', 'KanbanForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'KanbanForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Tarefa', 'TarefaForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TarefaForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Cadastro de Plano', 'PlanoForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'PlanoForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'TarefaSimpleList', 'TarefaSimpleList');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TarefaSimpleList'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'TarefaKanbanView', 'TarefaKanbanView');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'TarefaKanbanView'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Agendamento(Form)', 'AgendamentoCalendarForm');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'AgendamentoCalendarForm'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Agendamento(View)', 'AgendamentoCalendarFormView');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), (SELECT max(g.id) FROM system_group g) , (SELECT max(p.id) FROM system_program p where p.controller = 'AgendamentoCalendarFormView'));
INSERT INTO system_program (id, name, controller) VALUES( (SELECT max(p.id) + 1 FROM system_program p) , 'Teste', 'Teste');
INSERT INTO system_group_program (id, system_group_id, system_program_id) VALUES( (SELECT max(gp.id) + 1 FROM system_group_program gp), 1 , (SELECT max(p.id) FROM system_program p));